on:
  push:
    branches:
      - main
      - release-pages
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  feishu-pages:
    name: Feishu Pages Export
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Exporting
        env:
          FEISHU_APP_ID: ${{ secrets.FEISHU_APP_ID }}
          FEISHU_APP_SECRET: ${{ secrets.FEISHU_APP_SECRET }}
          FEISHU_SPACE_ID: '7273324757679325186'
          OUTPUT_DIR: ./dist
          ASSET_BASE_URL: 'https://longbridgeapp.github.io/feishu-pages/assets'
        uses: longbridgeapp/feishu-pages@main
      - name: Build Pages
        run: |
          cp dist/docs/**/* example-website/
          cp -R dist/assets example-website/public/
          yarn
          yarn workspace example-website build
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './example-website/.vitepress/dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
